### ISSUE TITLE
field check failed

### ISSUE THREAD

**Issue by kanoqwq** [tcort/tcadif#1]
When i try to process the LoTW's adi file
the script throw a error message:
errMsg:
err AdifError: field check failed
    at VUCC_GRIDS.validate (C:\Users\kano\Desktop\adif\node_modules\tcadif\lib\defs\FieldDef.js:86:23)
    at C:\Users\kano\Desktop\adif\node_modules\tcadif\lib\QSO.js:20:17
    at Array.forEach (<anonymous>)
    at new QSO (C:\Users\kano\Desktop\adif\node_modules\tcadif\lib\QSO.js:18:162)
    at AdifReader.processFields (C:\Users\kano\Desktop\adif\node_modules\tcadif\lib\AdifReader.js:35:29)
    at AdifReader.processQueue (C:\Users\kano\Desktop\adif\node_modules\tcadif\lib\AdifReader.js:50:22)
    at AdifReader._final (C:\Users\kano\Desktop\adif\node_modules\tcadif\lib\AdifReader.js:67:14)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5) {
  field: 'VUCC_GRIDS',
  value: 'PN03XN,PN13AN'
}

Adi file line at
<VUCC_GRIDS:13>PN03XN,PN13AN

**Comment by tcort** [comment]
The [ADIF v3.1.4 specification](http://www.adif.org.uk/314/ADIF_314.htm) specifically says that the grid squares in `VUCC_GRIDS` are "each four characters long".

![image](https://github.com/tcort/tcadif/assets/216720/139cc712-c986-4cbc-8b99-a243cffbdbdb)

`<VUCC_GRIDS:13>PN03XN,PN13AN`

The data you provided has grid squares which are each six characters long. It seems like the data being read does not conform to the ADIF v3.1.4 standard.
